(module 0
    (assign 1
        (id 1 a)
        (int_literal 1 5))
    (assign 2
        (id 2 b)
        (int_literal 2 7))
    (assign 3
        (id 3 c)
        (binop 3
            (id 3 a)
            (id 3 +)
            (int_literal 3 1)))
    (assign 4
        (id 4 d)
        (binop 4
            (id 4 b)
            (id 4 +)
            (id 4 a)))
    (assign 5
        (id 5 d)
        (binop 5
            (int_literal 5 8)
            (id 5 +)
            (binop 5
                (int_literal 5 1)
                (id 5 /)
