(module 0
    (for 1
        (id 1 i)
        (call 1
            (id 1 range)
            (expr_list 1
                (int_literal 1 10)))
        (stmt_list 2
            (if 2
                (compare 2
                    (id 2 i)
                    (id 2 ==)
                    (int_literal 2 6))
                (stmt_list 0
                    (break 0))
                ())
            (if 4
                (compare 4
                    (id 4 i)
                    (id 4 !=)
                    (int_literal 4 6))
                (stmt_list 5
                    (println 5
                        ()
                        (expr_list 5
                            (id 5 i))))
                ()))
