(module 0
    (assign 1
        (id 1 a)
        (dict_display 1
            (pair 1
                (string_literal 1 "hello")
                (int_literal 1 1))
            (pair 1
                (string_literal 1 "goodbye")
                (int_literal 1 3))))
    (println 2
        ()
        (expr_list 2
            (id 2 a)))
    (assign 3
        (id 3 b)
        (dict_display 3
            (pair 3
                (string_literal 3 "list")
                (list_display 3
                    (int_literal 3 1)
                    (int_literal 3 2)
                    (int_literal 3 3)))
            (pair 3
                (string_literal 3 "tuple")
                (tuple 3
                    (int_literal 3 4)
                    (int_literal 3 5)
                    (int_literal 3 6)))
            (pair 3
                (string_literal 3 "int")
                (int_literal 3 9))
            (pair 3
                (string_literal 3 "string")
                (string_literal 3 "this"))))
    (println 4
        ()
        (expr_list 4
            (id 4 b)))
    (def 5
        (id 5 foo)
        (formals_list 0)
        ()
        (block 6
            (println 6
                ()
                (expr_list 6
                    (string_literal 6 "FUNCTION")))
            (return 7
                (id 7 True))))
    (assign 8
        (id 8 c)
        (dict_display 8
            (pair 8
                (string_literal 8 "func")
                (id 8 foo))))
    (println 9
        ()
        (expr_list 9
            (call 9
                (subscription 9
                    (id 9 c)
                    (string_literal 9 "func"))
