(module 0
    (assign 1
        (id 1 a)
        (int_literal 1 3))
    (assign 2
        (id 2 b)
        (int_literal 2 5))
    (def 3
        (id 3 foo)
        (formals_list 0)
        ()
        (block 4
            (return 4
                (int_literal 4 5))))
    (assign 5
        (id 5 c)
        (binop 5
            (id 5 a)
            (id 5 or)
            (id 5 b)))
    (assign 6
        (id 6 c)
        (binop 6
            (id 6 c)
            (id 6 or)
            (id 6 b)))
    (assign 7
        (id 7 c)
        (binop 7
            (call 7
                (id 7 foo)
                (expr_list 0))
            (id 7 or)
