(module 0
    (def 1
        (id 1 a)
        (formals_list 0)
        ()
        (block 2
            (return 2
                (int_literal 2 3))))
    (def 3
        (id 3 b)
        (formals_list 0)
        ()
        (block 4
            (return 4
                (tuple 4
                    (int_literal 4 1)
                    (int_literal 4 2)
                    (int_literal 4 3)))))
    (println 5
        ()
        (expr_list 5
            (call 5
                (id 5 a)
                (expr_list 0))))
    (println 6
        ()
        (expr_list 6
            (call 6
                (id 6 b)
