(module 0
    (assign 1
        (id 1 li)
        (list_display 1
            (int_literal 1 1)
            (int_literal 1 3)
            (int_literal 1 4)
            (int_literal 1 5)
            (int_literal 1 6)
            (int_literal 1 7)
            (int_literal 1 8)
            (int_literal 1 9)
            (int_literal 1 10)
            (int_literal 1 11)
            (int_literal 1 12)))
    (subscription 2
        (id 2 li)
