(module 0
    (assign 1
        (typed_id 1
            (id 1 a)
            (type 1
                (id 1 int)
                (type_list 0)))
        (int_literal 1 10))
    (assign 2
        (typed_id 2
            (id 2 b)
            (type 2
                (id 2 $Type)
                (type_list 0)))
        (int_literal 2 8))
    (assign 3
        (typed_id 3
            (id 3 c)
            (type 3
                (id 3 list)
                (type_list 3
                    (type 3
                        (id 3 int)
                        (type_list 0)))))
