(module 0
    (for 1
        (id 1 i)
        (call 1
            (id 1 range)
            (expr_list 1
                (int_literal 1 10)))
        (stmt_list 2
            (if 2
                (compare 2
                    (id 2 i)
                    (id 2 ==)
                    (int_literal 2 6))
                (stmt_list 0
                    (continue 0))
                ())
            (println 4
                ()
                (expr_list 4
                    (id 4 i))))
