(module 0
    (unop 1
        (id 1 -)
        (unop 1
            (id 1 -)
            (unop 1
                (id 1 -)
                (unop 1
                    (id 1 -)
                    (unop 1
                        (id 1 -)
                        (unop 1
                            (id 1 -)
                            (unop 1
                                (id 1 -)
                                (unop 1
                                    (id 1 -)
